spring.application.name=payment-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=incidentai
spring.datasource.password=incidentai

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false