spring.application.name=order-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=incidentai
spring.datasource.password=incidentai

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false